#!/usr/bin/env bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "=== Harbor FM Docker setup ==="
echo ""

# Check for docker and compose
if ! command -v docker &>/dev/null; then
  echo "Error: docker is not installed or not in PATH." >&2
  exit 1
fi
if ! docker compose version &>/dev/null; then
  echo "Error: docker compose is not available. Need Docker Compose v2." >&2
  exit 1
fi

# Load existing .env if present (for defaults / overwrite prompt)
if [ -f .env ]; then
  echo "Existing .env found."
  read -r -p "Overwrite with new values? [y/N] " overwrite
  if [[ ! "$overwrite" =~ ^[yY] ]]; then
    echo "Using existing .env. Skipping prompts."
    set -a
    # shellcheck source=/dev/null
    source .env
    set +a
    DOMAIN="${DOMAIN:-localhost}"
    CERTBOT_EMAIL="${CERTBOT_EMAIL:-}"
    TZ="${TZ:-}"
  else
    overwrite_env=true
  fi
else
  overwrite_env=true
fi

if [ "${overwrite_env:-false}" = true ]; then
  echo ""
  read -r -p "Domain name (e.g. harborfm.example.com) [localhost]: " DOMAIN
  DOMAIN="${DOMAIN:-localhost}"

  read -r -p "Email for Let's Encrypt (required for real SSL, empty to skip certbot): " CERTBOT_EMAIL
  CERTBOT_EMAIL="${CERTBOT_EMAIL:-}"

  read -r -p "Optional timezone for fail2ban (e.g. America/New_York, Enter to skip): " TZ
  TZ="${TZ:-}"

  {
    echo "# Generated by docker-create.sh"
    echo "DOMAIN=$DOMAIN"
    echo "CERTBOT_EMAIL=$CERTBOT_EMAIL"
    [ -n "$TZ" ] && echo "TZ=$TZ"
  } > .env
  echo "Wrote .env"
  echo ""
fi

echo "Ensuring harborfm-docker-data directories exist..."
mkdir -p harborfm-docker-data/{data,secrets,certbot/webroot,certbot/certs,nginx/logs,redis,whisper/cache}

echo "Starting containers (build + up)..."
docker compose build
docker compose up -d

echo ""
echo "Waiting for nginx to be ready..."
for i in {1..30}; do
  if curl -s -o /dev/null -w "%{http_code}" --connect-timeout 2 "http://127.0.0.1/.well-known/acme-challenge/" 2>/dev/null | grep -q '404\|403'; then
    echo "Nginx is up."
    break
  fi
  if [ "$i" -eq 30 ]; then
    echo "Warning: nginx may not be ready yet. Certbot might fail; you can run it again later."
  fi
  sleep 1
done

if [ -n "$CERTBOT_EMAIL" ] && [ "$DOMAIN" != "localhost" ]; then
  echo ""
  read -r -p "Obtain Let's Encrypt certificate for $DOMAIN now? [Y/n] " run_certbot
  if [[ ! "$run_certbot" =~ ^[nN] ]]; then
    echo "Running certbot..."
    if docker compose run --rm certbot; then
      echo "Certificate obtained. Nginx will reload within ~60 seconds to use it."
    else
      echo "Certbot failed or skipped (e.g. rate limit, DNS not pointed). Run later: docker compose run --rm certbot"
    fi
  else
    echo "Skipped. Run when ready: docker compose run --rm certbot"
  fi
else
  echo ""
  if [ "$DOMAIN" = "localhost" ] || [ -z "$CERTBOT_EMAIL" ]; then
    echo "Domain is localhost or email not set - skipping certbot."
    echo "Edit .env (DOMAIN, CERTBOT_EMAIL), then run: docker compose run --rm certbot"
  fi
fi

echo ""
echo "=== Done ==="
echo "  App:     https://${DOMAIN}/ (or http:// if no cert yet)"
echo "  Renew:   docker compose run --rm certbot renew"
echo "  Logs:    docker compose logs -f"
echo "  Stop:    docker compose down"
