packages:
  - server
  - web
  - shared
  - docs
  - webrtc-service
  - e2e

ignoredBuiltDependencies:
  - argon2
  - cpu-features
  - esbuild
  - ssh2

onlyBuiltDependencies:
  - better-sqlite3
  - mediasoup