apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "harborfm.fullname" . }}-webrtc-recordings
  labels:
    {{- include "harborfm.labels" . | nindent 4 }}
    app.kubernetes.io/component: webrtc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.webrtc.size }}
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
