apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "harborfm.fullname" . }}-secrets
  labels:
    {{- include "harborfm.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.secrets.size }}
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
