apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harborfm.fullname" . }}-app
  labels:
    {{- include "harborfm.labels" . | nindent 4 }}
type: Opaque
stringData:
  _chart: "harborfm"
  {{- if .Values.setupId }}
  SETUP_ID: {{ .Values.setupId | quote }}
  {{- end }}
  {{- if .Values.recordingCallbackSecret }}
  RECORDING_CALLBACK_SECRET: {{ .Values.recordingCallbackSecret | quote }}
  {{- end }}
  {{- if and .Values.webrtc.enabled .Values.webrtc.serviceSecret }}
  WEBRTC_SERVICE_SECRET: {{ .Values.webrtc.serviceSecret | quote }}
  {{- end }}
  {{- if and .Values.webrtc.enabled .Values.webrtc.recordingCallbackSecret }}
  WEBRTC_RECORDING_CALLBACK_SECRET: {{ .Values.webrtc.recordingCallbackSecret | quote }}
  {{- end }}
