import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';
import { spawn } from 'child_process';
import { assertResolvedPathUnder, getDataDir } from './paths.js';

const GEOIP_CONF_FILENAME = 'GeoIP.conf';
const EDITION_IDS = 'GeoLite2-Country GeoLite2-City';

/**
 * Write a GeoIP.conf file for the GeoIP Update program and run geoipupdate
 * to download GeoLite2-Country and GeoLite2-City into the data directory.
 * Requires the geoipupdate binary to be installed (e.g. from
 * https://github.com/maxmind/geoipupdate/releases).
 *
 * Runs in the background; resolves when the process exits (success or failure).
 * @returns Promise that resolves to { ok: true } or { ok: false, error: string }
 */
export function runGeoIPUpdate(accountId: string, licenseKey: string): Promise<{ ok: boolean; error?: string }> {
  const dataDir = getDataDir();
  const confPath = join(dataDir, GEOIP_CONF_FILENAME);

  if (!accountId.trim() || !licenseKey.trim()) {
    return Promise.resolve({ ok: false, error: 'MaxMind Account ID and License Key are required' });
  }

  try {
    assertResolvedPathUnder(confPath, dataDir);
    
    // GeoIP.conf format: AccountID, LicenseKey, EditionIDs, DatabaseDirectory
    const conf = [
      '# Generated by HarborFM - do not edit; overwritten when MaxMind settings are saved',
      `AccountID ${accountId.trim()}`,
      `LicenseKey ${licenseKey.trim()}`,
      `EditionIDs ${EDITION_IDS}`,
      `DatabaseDirectory ${dataDir}`,
    ].join('\n');

    writeFileSync(confPath, conf, 'utf8');
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    return Promise.resolve({ ok: false, error: `Failed to write GeoIP.conf: ${msg}` });
  }

  return new Promise((resolve) => {
    const child = spawn('geoipupdate', ['-f', confPath], {
      stdio: ['ignore', 'pipe', 'pipe'],
      env: { ...process.env, GEOIPUPDATE_DB_DIR: dataDir },
    });

    let stderr = '';

    child.stderr?.on('data', (chunk: Buffer) => {
      stderr += chunk.toString();
    });

    child.on('error', (err) => {
      if ((err as NodeJS.ErrnoException).code === 'ENOENT') {
        resolve({
          ok: false,
          error:
            'GeoIP Update is not installed. Install it from https://github.com/maxmind/geoipupdate/releases and ensure geoipupdate is on PATH.',
        });
      } else {
        resolve({ ok: false, error: (err as Error).message });
      }
    });

    child.on('close', (code) => {
      if (code === 0) {
        resolve({ ok: true });
      } else {
        const msg = stderr.trim() || `geoipupdate exited with code ${code ?? 'unknown'}`;
        resolve({ ok: false, error: msg });
      }
    });
  });
}
